### ISSUE TITLE
🐞 Won't build on Flutter 3.0.0

### ISSUE THREAD

**Issue by nrubin29** [fluttercommunity/flutter_workmanager#382]
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [x] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| Workmanager version  | 0.5.0-dev.8 |

**Describe the error**
When attempting to compile an Android app with Flutter 3.0.0, the following error occurs:

```
e: /Users/.../flutter/.pub-cache/hosted/pub.dartlang.org/workmanager-0.5.0-dev.8/android/src/main/kotlin/be/tramckrijte/workmanager/BackgroundWorker.kt: (148, 21): Object is not abstract and does not implement abstract member public abstract fun error(p0: String, p1: String?, p2: Any?): Unit defined in io.flutter.plugin.common.MethodChannel.Result
e: /Users/.../flutter/.pub-cache/hosted/pub.dartlang.org/workmanager-0.5.0-dev.8/android/src/main/kotlin/be/tramckrijte/workmanager/BackgroundWorker.kt: (153, 25): 'error' overrides nothing
```

I ran into the same issue with my own plugin and fixed it by making the parameters of the method in question non-nullable.

**Comment by sunalwaysknows** [comment]
@nrubin29 hello👋, I created PR #383 to fix this question, meanwhile you can try to use my fock  https://github.com/sunalwaysknows/flutter_workmanager

**Comment by ened** [comment]
Thank you and the fix will land today. This issue is a duplicate of #379 and will be closed.
